### ISSUE TITLE
Does this crate have to use Bytes crate?

### ISSUE THREAD

**Issue by PonasKovas** [CrabCraftDev/CrabNBT#17]
Hello,

this seems like a nice NBT crate, but it's using `Bytes` and `BytesMut` everywhere for some reason and it's a bit of a dealbreaker for my project because I don't use the `bytes` crate. Does `crab_nbt` really depend on `Bytes` functionality? Wouldn't it be enough to use simple byte slices `&[u8]` or maybe `impl io::Read`/`impl io::Write`?

**Comment by Norbiros** [comment]
I was thinking about that. Today/tomorrow I'l try to modify our crate to make "bytes" as optional feature.

**Comment by PonasKovas** [comment]
Are you gonna release a new version to crates.io? 🙂

**Comment by Norbiros** [comment]
Done! [0.2.2](https://crates.io/crates/crab_nbt/0.2.2)

**Comment by PonasKovas** [comment]
The serde functions (which were precisely what I actually need) still use Bytes 😩 😩

**Comment by PonasKovas** [comment]
😢
