### ISSUE TITLE
[Feat]: Serialize to/from Struct

### ISSUE THREAD

**Issue by Norbiros** [CrabCraftDev/CrabNBT#2]
We need to develop a system where you can serialize NBT data into a struct and vice versa.

## Possible solutions:
 - Utilize `serde`, however, the order of fields in the NBT tag (tag id, name, content) may result in significant boilerplate code.
 - Implement custom derive macro.

**Comment by goteusz-maszyk** [comment]
a trait NBTSerialisable?

**Comment by Norbiros** [comment]
Ymmm, maybe, but it isn't main reason. We need to have system that converts object to bytes and reverse. So we can define how nbt data can look in code.
