### ISSUE TITLE
It is assumed that the root tag is always a compound

### ISSUE THREAD

**Issue by ARitz-Cracker** [CrabCraftDev/CrabNBT#21]
Basically, I'm trying to make a [servers.dat](https://minecraft.wiki/w/Servers.dat_format) file, doesn't seem like I'm able to do that with this crate, as the root value is a list.

Additionally, I'm not sure if the "root" tag itself being named is a good assumption to have, see https://minecraft.wiki/w/Java_Edition_level_format#poi_format .

**Comment by ARitz-Cracker** [comment]
Ah, it appears I've been a victim of potentially misleading documentation, turns out the root tag did have a name and it was an empty string

**Comment by SzczurekYT** [comment]
Was it a problem with our documentation or some other one?
If it was ours, is there anything we could improve?

**Comment by ARitz-Cracker** [comment]
> Was it a problem with our documentation or some other one? If it was ours, is there anything we could improve?

Hey so:
1. I took the minecraft wiki page at face value, I didn't know that the root NBT _had_ to be a compound with a name, and the wiki page didn't make it obvious that the root node was a compound named "". Though I don't know whether or not that's "common knowledge' in this space.
2. One thing that _could_ be improved is making the "invalid state" of the serde error messages more descriptive, e.g. "root node must be a named compound but got a {} instead".
